# Generated by Django 3.2.6 on 2021-09-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('desease', models.CharField(max_length=60)),
                ('age', models.IntegerField(max_length=3)),
            ],
        ),
    ]
